### ISSUE TITLE
previews for X are not looking fine

### ISSUE THREAD

**Issue by Anna15170221** [Bithomp/frontend-react#504]
The ones which need to be fixed for X: 
- the pages where no special preview is set and we are using the preview from the landing page by default. For example,
/tokens 
/services/check
/amm
/trustline
/domains
<img width="587" height="154" alt="Image" src="https://github.com/user-attachments/assets/4cc8ae2a-1f52-4e58-8c99-f6a22eff4ef4" />

<img width="587" height="154" alt="Image" src="https://github.com/user-attachments/assets/bcdffe1e-34b6-4c18-bbb5-76ca89679f16" />

But for the landing page the preview looks fine

**Comment by ihomp** [comment]
I've deploying a possible fix - but we will need to test

**Comment by ihomp** [comment]
deployed

I've just tested it, it still the same.. but lets wait - may be it's a cache issue now

**Comment by ihomp** [comment]
<img width="532" height="264" alt="Image" src="https://github.com/user-attachments/assets/8e97bc1f-018a-4853-b9c7-3b658925cabd" />

fixed?

**Comment by Anna15170221** [comment]
@ihomp I will probably test a bit later. Because at the moment for me it's partially fixed-partially not...

<img width="562" height="244" alt="Image" src="https://github.com/user-attachments/assets/eeadeef2-40a4-4ce4-a66b-b905c423ccfc" />
<img width="562" height="244" alt="Image" src="https://github.com/user-attachments/assets/ddf8ba83-fc63-4ec7-85b1-199eb252c185" />

**Comment by Anna15170221** [comment]
seems like not fixed
<img width="562" height="244" alt="Image" src="https://github.com/user-attachments/assets/cd435aec-0030-42ae-92bd-20822712497d" />
<img width="562" height="244" alt="Image" src="https://github.com/user-attachments/assets/719ce362-9fa9-491c-b157-d6a71d4bbf5c" />
<img width="562" height="244" alt="Image" src="https://github.com/user-attachments/assets/07218390-6269-4ebf-bb9b-fdf8865bf3c0" />

**Comment by Anna15170221** [comment]
Earlier for the page /nft there was the picture of nft in X - currently the default picture is shown there, and I'd rather return the picture of nft

<img width="588" height="186" alt="Image" src="https://github.com/user-attachments/assets/e5db0ce0-e0cd-4419-af53-003d0c594753" />

In Linkedin it's fine - with nft picture

<img width="739" height="258" alt="Image" src="https://github.com/user-attachments/assets/8b5c8a82-4d1e-457c-9629-5b500120688b" />

**Comment by ihomp** [comment]
> Earlier for the page /nft there was the picture of nft in X - currently the default picture is shown there, and I'd rather return the picture of nft
> 
> <img alt="Image" width="588" height="186" src="https://private-user-images.githubusercontent.com/152614606/473690177-e5db0ce0-e0cd-4419-af53-003d0c594753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQyOTAwMjAsIm5iZiI6MTc1NDI4OTcyMCwicGF0aCI6Ii8xNTI2MTQ2MDYvNDczNjkwMTc3LWU1ZGIwY2UwLWUwY2QtNDQxOS1hZjUzLTAwM2QwYzU5NDc1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNFQwNjQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmNhMzM0M2NlZjIxNzFkNjAwNTUxNzYxN2RkNWQ3MDE2YTA5ZmIwMmY1M2NlMDRjMTU1NDQzOGE5NGQ2YTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CMzOeKuAUMlzAm5FStlI-rmG4Lwa1dQIddH-SZUgd2k">
> In Linkedin and discord it's fine - with nft picture - which is better I think.
> 
> <img alt="Image" width="739" height="258" src="https://private-user-images.githubusercontent.com/152614606/473690204-8b5c8a82-4d1e-457c-9629-5b500120688b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQyOTAwMjAsIm5iZiI6MTc1NDI4OTcyMCwicGF0aCI6Ii8xNTI2MTQ2MDYvNDczNjkwMjA0LThiNWM4YTgyLTRkMWUtNDU3Yy05NjI5LTViNTAwMTIwNjg4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNFQwNjQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDFhNzM1ZTRlMGM0MmE0YzIxYWVlNGYwMDAyZGI2MTc2YmVmNjc3MWRkMWExZTIxNThmMTM0YWE0MjE5NDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ippGS3LS2zNU_pAYKfwpu4XgvDAFKtYZG_XArgF9YYI">

ooops, that is bad.. 
fixing https://github.com/Bithomp/frontend-react/commit/64b012c0af062e9dc3a7b9bce6d9b05ba7fa5d4c

**Comment by ihomp** [comment]
The problem in twitter caching 
so, if you try something like 

https://bithomp.com/en/services/trustline?v=2

it will show the right image

**Comment by ihomp** [comment]
https://bithomp.com/en/nft/000822B03EA060FD1026C04B2D390CC132D07D600DA9B0822A0ECF0500000C69?v=2 

for nfts

**Comment by ihomp** [comment]
@Anna15170221 when the preview is wrong, use in the end someting like ?v=2 or &v=2 (if the link already has a ? in it).

**Comment by ihomp** [comment]
You can close it if you think we are good =) 
the cache will update eventually
